# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          metrics_path: ''
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:7000']
            - targets: ['localhost:7001']

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  file:
    path: /var/log/otel.log

service:
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,file]
  telemetry:
    logs:
      level: "debug"
      encoding: "console"
    metrics:
      address: ":8888"
