# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

extensions:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          metrics_path: ''
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:7001']

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  file:
    path: /var/log/otel.log
service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,file]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,file]
    metrics:
      receivers: [otlp]
      #receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging,file]
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: ":8888"
