# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          metrics_path: ''
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:7001']
          # as of May, 2022 attempting to rename matrics fails with "metric renaming using metric_relabel_configs is disallowed"
          # see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5001
          #metric_relabel_configs:
            #- source_labels: [ __name__ ]
              #regex: "(.*).(.*)"
              #replacement: "${1}_${2}"
              #target_label: "__name__"

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  file:
    path: /var/log/otel.log

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [logging,file]
  telemetry:
    logs:
      level: "debug"
      encoding: "console"
    metrics:
      address: ":8889"
